### ISSUE TITLE
How do I generate StarRailRes from StarRailData,thanks

### ISSUE THREAD

**Issue by weiwoq159** [Mar-7th/StarRailRes#4]

**Comment by mobyw** [comment]
Since the data update script is not yet fully automated, it is currently executed locally and released after proofreading. If full automation can be realized in the future, scripts will be added to the repo and updated with GitHub Action.

If you need the processing of a certain index file, I can directly reply the scripts here. If you need other index files or need to add additional fields to an existing index file, please post related issues directly.

**Comment by weiwoq159** [comment]
> Since the data update script is not yet fully automated, it is currently executed locally and released after proofreading. If full automation can be realized in the future, scripts will be added to the repo and updated with GitHub Action.
> 
> If you need the processing of a certain index file, I can directly reply the scripts here. If you need other index files or need to add additional fields to an existing index file, please post related issues directly.

thanks, and I want to get image resources where do I go to get them. There is no picture of danhengil in the file.

**Comment by mobyw** [comment]
Only character config exists in game pack will be placed in the repo. There is no danhengil now.
