### ISSUE TITLE
How do I get params

### ISSUE THREAD

**Issue by weiwoq159** [Mar-7th/StarRailRes#7]
What are the values of the fields "affix", "ratio", "percent", etc. obtained from in properties.json?thanks

**Comment by mobyw** [comment]
`affix` indicates whether it is a relic affix

`ratio` indicates whether it is a percentage addition to `field`

`percent` indicates whether it is shown as a percentage value

**Comment by weiwoq159** [comment]
but relic main affix or relic sub affix has no 'PhysicalResistance' and StarRailData has no AllDamageTypeAddedRatio. So I'm a bit confused as to where you got the values for 'affix' from.

**Comment by mobyw** [comment]
properties of character skill tree and light cone is also included.

some properties is not include in StarRailData because they are also not include in game config, and are processed in other steps instead of property. 

the repo provides unified properties config to allow dealing all properties at the same time.

**Comment by weiwoq159** [comment]
I see. Thank you
